# exercise

Jeg har lavet mine endpoints i min flask folder på min egen notebook server, men jeg ved ikke hvordan jeg skal aflevere det igennem jupiter, men koden kan afvikles hvis startes igennem vs-code

In [5]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv('./data/cars.csv')
con_str = "mysql+mysqlconnector://root:root@db/db"
engine = create_engine(con_str)
#connection = engine.raw_connection()
df.to_sql('cars_db',con=engine, if_exists='append', index = False)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,36945.0,33337.0,3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820.0,21761.0,2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,26990.0,24647.0,2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,33195.0,30299.0,3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755.0,39014.0,3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565.0,38203.0,2.4,5.0,197.0,21.0,28.0,3450.0,105.0,186.0
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565.0,40083.0,2.3,5.0,242.0,20.0,26.0,3450.0,105.0,186.0
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210.0,42573.0,2.9,6.0,268.0,19.0,26.0,3653.0,110.0,190.0
426,Volvo,V40,Wagon,Europe,Front,26135.0,24641.0,1.9,4.0,170.0,22.0,29.0,2822.0,101.0,180.0
427,Volvo,XC70,Wagon,Europe,All,35145.0,33112.0,2.5,5.0,208.0,20.0,27.0,3823.0,109.0,186.0

# Endpoints

In [ ]:

#!flask/bin/python
from flask import Flask, jsonify, abort, request
import mysql.connector as mysql

app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'

@app.route('/api/car/<int:id>', methods=['GET'])
def get_by_id(id):
    ## connecting to the database using 'connect()' method
    cnx = mysql.connect(host = "db", user = "root", passwd = "root", db = "db")
    # cursor = cnx.cursor()

    curA = cnx.cursor()
    

    
    query = ("SELECT * FROM cars_db WHERE Id = %s;")


    
    curA.execute(query, (id,))
    result = curA.fetchall()
    return str(result)

@app.route('/api/car', methods=['GET'])
def get_all():
    ## connecting to the database using 'connect()' method
    cnx = mysql.connect(host = "db", user = "root", passwd = "root", db = "db")
    # cursor = cnx.cursor()

    curA = cnx.cursor()
    

    
    query = ("SELECT * FROM cars_db;")


    
    curA.execute(query)
    result = curA.fetchall()
    return jsonify(result)
    
@app.route('/api/car/brand/<brand>', methods=['GET'])
def get_by_brand(brand):
    ## https://code-maven.com/flask-routes
    ## connecting to the database using 'connect()' method
    cnx = mysql.connect(host = "db", user = "root", passwd = "root", db = "db")
    # cursor = cnx.cursor()

    curA = cnx.cursor()
    

    
    query = ("SELECT * FROM cars_db WHERE make = %s;")


    
    curA.execute(query, (brand,))
    result = curA.fetchall()
    return jsonify(result)

@app.route('/api/car', methods=['POST'])
def add_car():
    ## connecting to the database using 'connect()' method
    cnx = mysql.connect(host = "db", user = "root", passwd = "root", db = "db")
    # cursor = cnx.cursor()

    curA = cnx.cursor(prepared=True)
    

    
    query = ("INSERT INTO cars_db (Make, Model, Type, Origin, DriveTrain, MSRP, Invoice, EngineSize, Cylinders, Horsepower, MPG_City, MPG_Highway, Weight, Wheelbase, Length) VALUES (%s, %s, %s ,%s, %s, %s ,%s, %s, %s ,%s, %s, %s ,%s, %s, %s);")
    val = (request.json['Make'], request.json['Model'], request.json['Type'], request.json['Origin'], request.json['DriveTrain'], request.json['MSRP'], request.json['Invoice'],request.json['EngineSize'],request.json['Cylinders'],request.json['Horsepower'], request.json['MPG_City'], request.json['MPG_Highway'], request.json['Weight'], request.json['Wheelbase'], request.json['Length'])
    
    
    curA.execute(query, val)
    cnx.commit()
    result = str(curA.lastrowid) + " record inserted."
    curA.close()
    cnx.close()
    
    return jsonify(result)

@app.route('/api/car/<int:id>', methods=['DELETE'])
def delete_car(id):
    ## connecting to the database using 'connect()' method
    cnx = mysql.connect(host = "db", user = "root", passwd = "root", db = "db")
    # cursor = cnx.cursor()

    curA = cnx.cursor(prepared=True)
    

    
    query = ("DELETE FROM cars_db WHERE Id = %s;")


    
    curA.execute(query, (id,))
    cnx.commit()
    result = str(id) + " deleted."
    curA.close()
    cnx.close()
    
    return jsonify(result)